exports.create = {
  KUnit: [
    { unitName: 'hkb7', unit: 7, title: 'In the city 1', type: 'hack_b' },
    { unitName: 'hkb8', unit: 8, title: 'In the city 2', type: 'hack_b' },
    { unitName: 'hkb9', unit: 9, title: 'House & Neighbourhood 1', type: 'hack_b' },
    { unitName: 'hkb10', unit: 10, title: 'House & Neighbourhood 2', type: 'hack_b' },
    { unitName: 'hkb11', unit: 11, title: 'Travelling & Tourist activities 1', type: 'hack_b' },
    { unitName: 'hkb12', unit: 12, title: 'Travelling & Tourist activities 2', type: 'hack_b' },
    { unitName: 'hkb13', unit: 13, title: 'Holidays & Culture 1', type: 'hack_b' },
    { unitName: 'hkb14', unit: 14, title: 'Holidays & Culture 2', type: 'hack_b' },
    { unitName: 'hkb15', unit: 15, title: 'Weather & Seasons', type: 'hack_b' },
    { unitName: 'hkb16', unit: 16, title: 'Food, Drinks & Cuisine 1', type: 'hack_b' },
    { unitName: 'hkb17', unit: 17, title: 'Food, Drinks & Cuisine 2', type: 'hack_b' },
    { unitName: 'hkb18', unit: 18, title: 'Food, Drinks & Cuisine 3', type: 'hack_b' },
    { unitName: 'hkb19', unit: 19, title: 'Daily diet, Fruits & Vegetables 1', type: 'hack_b' },
    { unitName: 'hkb20', unit: 20, title: 'Daily diet, Fruits & Vegetables 2', type: 'hack_b' },
    { unitName: 'hkb21', unit: 21, title: 'Country life & Nature 1', type: 'hack_b' },
    { unitName: 'hkb22', unit: 22, title: 'Country life & Nature 2', type: 'hack_b' },
    { unitName: 'hkb23', unit: 23, title: 'Health & Diseases 1', type: 'hack_b' },
    { unitName: 'hkb24', unit: 24, title: 'Health & Diseases 2', type: 'hack_b' },
    { unitName: 'hkb25', unit: 25, title: 'Treatment & Medicine', type: 'hack_b' },
    { unitName: 'hkb26', unit: 26, title: 'Relaxation & Resting', type: 'hack_b' },
    { unitName: 'hkb27', unit: 27, title: 'Sport & Exercising 1', type: 'hack_b' },
    { unitName: 'hkb28', unit: 28, title: 'Sport & Exercising 2', type: 'hack_b' },
    { unitName: 'hkb29', unit: 29, title: 'Traffic & Transport 1', type: 'hack_b' },
    { unitName: 'hkb30', unit: 30, title: 'Traffic & Transport 2', type: 'hack_b' },
    { unitName: 'hkb31', unit: 31, title: 'Music & Arts 1', type: 'hack_b' },
    { unitName: 'hkb32', unit: 32, title: 'Music & Arts 2', type: 'hack_b' },
    { unitName: 'hkb33', unit: 33, title: 'Celebrities & Fame', type: 'hack_b' },
    { unitName: 'hkb34', unit: 34, title: 'Social media & Technology 1', type: 'hack_b' },
    { unitName: 'hkb35', unit: 35, title: 'Social media & Technology 2', type: 'hack_b' },
    { unitName: 'hkb36', unit: 36, title: 'Personalities & Appearance 1', type: 'hack_b' },
    { unitName: 'hkb37', unit: 37, title: 'Personalities & Appearance 2', type: 'hack_b' },
    { unitName: 'hkb38', unit: 38, title: 'Relationships & Feelings 1', type: 'hack_b' },
    { unitName: 'hkb39', unit: 39, title: 'Relationships & Feelings 2', type: 'hack_b' },
    { unitName: 'hkb40', unit: 40, title: 'Entertainment', type: 'hack_b' },
    { unitName: 'hkb41', unit: 41, title: 'Shopping', type: 'hack_b' },
    { unitName: 'hkb42', unit: 42, title: 'Accessories & Clothes 1', type: 'hack_b' },
    { unitName: 'hkb43', unit: 43, title: 'Accessories & Clothes 2', type: 'hack_b' },
    { unitName: 'hkb44', unit: 44, title: 'Daily routines & Free-time activities 1', type: 'hack_b' },
    { unitName: 'hkb45', unit: 45, title: 'Daily routines & Free-time activities 2', type: 'hack_b' },
    { unitName: 'hkb46', unit: 46, title: 'Education', type: 'hack_b' },
    { unitName: 'hkb47', unit: 47, title: 'Crime & Politics 1', type: 'hack_b' },
    { unitName: 'hkb48', unit: 48, title: 'Crime & Politics 2', type: 'hack_b' },
    { unitName: 'hkb49', unit: 49, title: 'Business & Commerce', type: 'hack_b' },
    { unitName: 'hkb50', unit: 50, title: 'Space', type: 'hack_b' },
  ]
};
